# Generated by Django 5.2.16 on 2026-07-22 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad de Combustible (Litros)')),
                ('motivo', models.TextField(verbose_name='Motivo de la Solicitud')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada por Director'), ('rechazada', 'Rechazada por Director'), ('en_proceso_petroleo', 'En Proceso - Dpto. Petróleo'), ('enviada_almacen', 'Enviada a Almacén'), ('distribuida', 'Combustible Distribuido')], default='borrador', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('comentario_director', models.TextField(blank=True, null=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Combustible',
                'verbose_name_plural': 'Solicitudes de Combustible',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
