# Generated by Django 5.2.11 on 2026-07-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_combustible', models.CharField(max_length=50, verbose_name='Tipo de Combustible')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa')),
                ('tipo_vehiculo', models.CharField(max_length=50, verbose_name='Tipo de Vehículo')),
                ('chapa', models.CharField(max_length=50, verbose_name='Chapa')),
                ('actividad', models.TextField(max_length=50, verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'ordering': ['tipo_vehiculo'],
            },
        ),
    ]
