# Generated by Django 5.2.11 on 2026-07-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0002_transporte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transporte',
            options={'ordering': ['empresa'], 'verbose_name': 'Transporte', 'verbose_name_plural': 'Transportes'},
        ),
        migrations.AlterField(
            model_name='transporte',
            name='actividad',
            field=models.TextField(verbose_name='Actividad'),
        ),
    ]
