# Generated by Django 5.2.11 on 2026-07-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0003_alter_transporte_options_alter_transporte_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='actividad',
        ),
    ]
