# Generated by Django 5.2.11 on 2026-07-30 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0004_remove_transporte_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcombustible',
            name='cantidad_litros',
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=50, verbose_name='Actividad')),
                ('via_blanca', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Vía Blanca')),
                ('cte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CTE')),
                ('ic', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='I/C')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='combustible.solicitudcombustible')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combustible.transporte', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitudes',
            },
        ),
    ]
