# Generated by Django 5.2.11 on 2026-07-30 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0005_remove_solicitudcombustible_cantidad_litros_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudcombustible',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Solicitud de Combustible', 'verbose_name_plural': 'Solicitudes de Combustible'},
        ),
        migrations.RemoveField(
            model_name='solicitudcombustible',
            name='comentario_director',
        ),
        migrations.RemoveField(
            model_name='solicitudcombustible',
            name='director',
        ),
        migrations.RemoveField(
            model_name='solicitudcombustible',
            name='fecha_aprobacion',
        ),
        migrations.RemoveField(
            model_name='solicitudcombustible',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='solicitudcombustible',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='solicitudcombustible',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='solicitudcombustible',
            name='solicitante',
        ),
        migrations.AddField(
            model_name='solicitudcombustible',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='solicitudcombustible',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudcombustible',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de la Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudcombustible',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada por Director'), ('rechazada', 'Rechazada por Director')], default='pendiente', max_length=30),
        ),
    ]
