# Generated by Django 5.2.11 on 2026-07-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0006_alter_solicitudcombustible_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcombustible',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada por Director'), ('rechazada', 'Rechazada por Director')], default='borrador', max_length=30),
        ),
    ]
