# Generated by Django 5.2.11 on 2026-07-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0007_alter_solicitudcombustible_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesolicitud',
            name='cte',
        ),
        migrations.RemoveField(
            model_name='detallesolicitud',
            name='ic',
        ),
        migrations.RemoveField(
            model_name='detallesolicitud',
            name='via_blanca',
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='cant_abastecer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cant. a Abastecer'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='ic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='I/C'),
        ),
    ]
