# Generated by Django 5.2.11 on 2026-08-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0008_remove_detallesolicitud_cte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcombustible',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo del Rechazo'),
        ),
    ]
