# Generated by Django 5.2.11 on 2026-08-07 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0009_solicitudcombustible_motivo_rechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespachoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Solicitud')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('subtotal_consumo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal de Consumo')),
                ('subtotal_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal de Venta')),
                ('total_general', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total General')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Extracción'), ('extraido', 'Combustible Extraído'), ('suministrado', 'Suministrado a Vehículos')], default='pendiente', max_length=20, verbose_name='Estado del Despacho')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='combustible.solicitudcombustible')),
            ],
            options={
                'verbose_name': 'Despacho de Combustible',
                'verbose_name_plural': 'Despachos de Combustible',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
