# Generated by Django 5.2.11 on 2026-08-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0010_despachocombustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesolicitud',
            name='cant_abastecer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cant. a Abastecer'),
        ),
    ]
