# Generated by Django 5.2.11 on 2026-08-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0011_alter_detallesolicitud_cant_abastecer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuministroCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Suministro')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('tipo_combustible', models.CharField(max_length=50, verbose_name='Tipo de Combustible')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad de Combustible')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Nota')),
            ],
            options={
                'verbose_name': 'Suministro de Combustible',
                'verbose_name_plural': 'Suministros de Combustible',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
