# Generated by Django 5.2.11 on 2026-08-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0012_suministrocombustible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suministrocombustible',
            options={},
        ),
        migrations.AddField(
            model_name='suministrocombustible',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Validar'), ('validado', 'Validado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
