# Generated by Django 5.2.11 on 2026-08-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0013_alter_suministrocombustible_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Recepción'), ('recibido', 'Recibido en Almacén')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('despacho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepcion_almacen', to='combustible.despachocombustible')),
            ],
            options={
                'verbose_name': 'Recepción de Almacén',
                'verbose_name_plural': 'Recepciones de Almacén',
            },
        ),
    ]
